### PR TITLE
Add image sending

### PR DESCRIPTION
**Pull request by Sorunome**
This adds the ability to send images via
```
sendImage({
    file: '/path/to/image.jpg',
    name: 'name_to_display_on_skype.jpg'
}, threadId);
```

### CODE REVIEW

**Comment by Sorunome** [comment]
I am not very familiar with typescript, could someone please help me resolving the last few lint errors?

**Comment by demurgos** [comment]
Thanks for your PR. I'll take a look at it (and the other issues 😛)

**Comment by demurgos** [comment]
Thanks you for your contribution. I fixed the few issues in #47, please use a feature-branch next time (instead of master) so its easier to patch the branch of your PR.

Overall it seems fine, I checked that it did not break the library but I did not have the code to actually test if it works so I trust you for this. I'd like to spend some time this week on this library so I'll try to come up with better tests.
Note that even if I'm merging now, the XML string sent to Skype should be properly sanitized (instead of concatenating the values). I'll open an issue for this.

**Comment by Sorunome** [comment]
Thank you for merging it and I'll keep the branch stuff in mind for next time.

**Pull request closed without merging**
